import AddRounded from '@mui/icons-material/AddRounded'
import DataObjectRounded from '@mui/icons-material/DataObjectRounded'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, LinearProgress, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { MapLegend } from '../components/common/MapLegend'
import { PageHeader } from '../components/common/PageHeader'
import { SurveyCanvas } from '../components/common/SurveyCanvas'
import { useAuth } from '../hooks/useAuth'
import { useCoverageLayers } from '../hooks/useCoverageLayers'
import { useSurveyAreaStore } from '../stores/survey-area-store'
import type { GeoJSONFeature } from '../types/api'
import type { CreateSurveyArea } from '../types/survey-area'

const defaultBoundary:GeoJSONFeature={type:'Feature',properties:{source:'manual'},geometry:{type:'Polygon',coordinates:[[[0,0],[1200,0],[1200,720],[0,720],[0,0]]]}}
export function AreasPage(){const{hasRole}=useAuth();const{items,selected,loading,fetch,select,create}=useSurveyAreaStore();const[open,setOpen]=useState(false);const[drawer,setDrawer]=useState(false);const[form,setForm]=useState<CreateSurveyArea>({area_code:'AREA-NEW',name:'新建离线测区',boundary_geojson:defaultBoundary,target_resolution_m:20,coordinate_system:'EPSG:32650',default_swath_m:180,owner_team:'海洋测绘组'});useEffect(()=>{void fetch()},[fetch]);const layers=useCoverageLayers(selected);const legends=useMemo(()=>layers.map(layer=>({label:layer.label,color:layer.color,pattern:layer.fill?'fill' as const:'solid' as const})),[layers]);const submit=async()=>{await create(form);setOpen(false)};return <>
  <PageHeader eyebrow="SURVEY BOUNDARY REGISTER" title="测区管理" description="维护米制投影边界、目标分辨率和覆盖摘要；归档测区保留历史证据但停止新增规划。" actions={<><Tooltip title="刷新"><IconButton aria-label="刷新测区" onClick={()=>void fetch()}><RefreshRounded/></IconButton></Tooltip>{hasRole('admin','survey_planner')&&<Button variant="contained" startIcon={<AddRounded/>} onClick={()=>setOpen(true)}>新建测区</Button>}</>}/>{loading&&<LinearProgress/>}
  <Box className="split-workspace"><Box className="table-pane"><Box className="section-heading"><Typography variant="h6">测区清单</Typography><Typography variant="caption">{items.length} 个边界版本</Typography></Box><Box className="data-table-wrap"><Table size="small"><TableHead><TableRow><TableCell>测区</TableCell><TableCell>投影 / 分辨率</TableCell><TableCell>覆盖摘要</TableCell><TableCell>责任团队</TableCell><TableCell>状态</TableCell></TableRow></TableHead><TableBody>{items.map(item=><TableRow key={item.id} hover selected={selected?.id===item.id} onClick={()=>select(item)} className="selectable-row"><TableCell><Typography fontWeight={750}>{item.area_code}</Typography><Typography variant="caption" color="text.secondary">{item.name}</Typography></TableCell><TableCell>{item.coordinate_system}<Typography variant="caption" display="block">{item.target_resolution_m} m · 扫幅 {item.default_swath_m} m</Typography></TableCell><TableCell>{item.summary.plan_count} 套规划<Typography variant="caption" display="block">覆盖 {(item.summary.latest_coverage_ratio*100).toFixed(1)}% · 缺口 {item.summary.open_gap_count}</Typography></TableCell><TableCell>{item.owner_team}</TableCell><TableCell><Chip size="small" variant="outlined" label={item.status}/></TableCell></TableRow>)}</TableBody></Table></Box></Box>
    <Box className="evidence-pane"><Box className="section-heading"><Box><Typography variant="overline">BOUNDARY EVIDENCE</Typography><Typography variant="h6">{selected?.name??'选择测区'}</Typography></Box><Tooltip title="查看 GeoJSON"><span><IconButton aria-label="查看测区 GeoJSON" disabled={!selected} onClick={()=>setDrawer(true)}><DataObjectRounded/></IconButton></span></Tooltip></Box><SurveyCanvas layers={layers}/><MapLegend items={legends}/>{selected&&<Box component="dl" className="detail-grid"><Box><Typography component="dt">面积坐标系</Typography><Typography component="dd">{selected.coordinate_system}</Typography></Box><Box><Typography component="dt">边界版本</Typography><Typography component="dd">V{selected.version}</Typography></Box><Box><Typography component="dt">处理运行</Typography><Typography component="dd">{selected.summary.processed_runs}</Typography></Box><Box><Typography component="dt">当前状态</Typography><Typography component="dd">{selected.status}</Typography></Box></Box>}</Box></Box>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>新建投影测区</DialogTitle><DialogContent><Stack gap={2} sx={{pt:1}}><TextField label="测区编号" value={form.area_code} onChange={event=>setForm({...form,area_code:event.target.value})}/><TextField label="名称" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth label="坐标系" value={form.coordinate_system} onChange={event=>setForm({...form,coordinate_system:event.target.value})}/><TextField fullWidth label="分辨率 (m)" type="number" value={form.target_resolution_m} onChange={event=>setForm({...form,target_resolution_m:Number(event.target.value)})}/></Stack><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth label="默认扫幅 (m)" type="number" value={form.default_swath_m} onChange={event=>setForm({...form,default_swath_m:Number(event.target.value)})}/><TextField fullWidth label="责任团队" value={form.owner_team} onChange={event=>setForm({...form,owner_team:event.target.value})}/></Stack><TextField label="边界 GeoJSON" multiline minRows={7} value={JSON.stringify(form.boundary_geojson,null,2)} onChange={event=>{try{setForm({...form,boundary_geojson:JSON.parse(event.target.value)})}catch{}}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>取消</Button><Button variant="contained" onClick={()=>void submit()}>创建测区</Button></DialogActions></Dialog>
  <GeometryDetailDrawer open={drawer} onClose={()=>setDrawer(false)} title={selected?.name??'测区边界'} geometry={selected?.boundary_geojson} metadata={selected?{'测区编号':selected.area_code,'投影坐标':selected.coordinate_system,'版本':selected.version}:undefined}/>
  </>}
