import FilterAltOutlined from '@mui/icons-material/FilterAltOutlined'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import VisibilityOutlined from '@mui/icons-material/VisibilityOutlined'
import { Box, Button, FormControl, IconButton, InputLabel, LinearProgress, MenuItem, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import { useCallback, useEffect, useState } from 'react'
import { auditApi } from '../api/audit'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { PageHeader } from '../components/common/PageHeader'
import type { AuditEvent, GeoJSONFeature } from '../types/api'

function parseGeometry(event:AuditEvent|null):GeoJSONFeature|undefined{if(!event)return;try{const data=JSON.parse(event.after_json) as Record<string,unknown>;for(const key of ['boundary_geojson','line_geojson','track_geojson','gap_geojson','recommended_line_geojson']){const value=data[key] as GeoJSONFeature|undefined;if(value?.type==='Feature')return value}}catch{return}}
export function AuditPage(){const[items,setItems]=useState<AuditEvent[]>([]);const[loading,setLoading]=useState(false);const[requestID,setRequestID]=useState('');const[entity,setEntity]=useState('');const[actor,setActor]=useState('');const[selected,setSelected]=useState<AuditEvent|null>(null);const fetch=useCallback(async()=>{setLoading(true);try{const query=new URLSearchParams({page_size:'100'});if(requestID)query.set('request_id',requestID);if(entity)query.set('entity_type',entity);if(actor)query.set('actor',actor);const response=await auditApi.list(`?${query}`);setItems(response.data)}finally{setLoading(false)}},[requestID,entity,actor]);useEffect(()=>{void fetch()},[fetch]);return <>
  <PageHeader eyebrow="IMMUTABLE CHANGE JOURNAL" title="审计中心" description="按 request ID、实体和操作者追溯四类核心实体的前后快照与算法输入证据。" actions={<Tooltip title="刷新"><IconButton aria-label="刷新审计" onClick={()=>void fetch()}><RefreshRounded/></IconButton></Tooltip>}/>
  <Stack direction={{xs:'column',md:'row'}} gap={1.5} className="filter-bar"><TextField size="small" label="request ID" value={requestID} onChange={event=>setRequestID(event.target.value)}/><TextField size="small" label="操作者" value={actor} onChange={event=>setActor(event.target.value)}/><FormControl size="small" sx={{minWidth:180}}><InputLabel>实体</InputLabel><Select label="实体" value={entity} onChange={event=>setEntity(event.target.value)}><MenuItem value="">全部实体</MenuItem><MenuItem value="survey_area">测区</MenuItem><MenuItem value="transect_plan">测线规划</MenuItem><MenuItem value="sonar_run">声呐运行</MenuItem><MenuItem value="coverage_gap">覆盖缺口</MenuItem></Select></FormControl><Button variant="contained" startIcon={<FilterAltOutlined/>} onClick={()=>void fetch()}>筛选</Button></Stack>{loading&&<LinearProgress/>}
  <Box className="audit-summary"><div><span>审计记录</span><strong>{items.length}</strong></div>{['survey_area','transect_plan','sonar_run','coverage_gap'].map(type=><div key={type}><span>{type}</span><strong>{items.filter(item=>item.entity_type===type).length}</strong></div>)}</Box><Box className="data-table-wrap"><Table size="small"><TableHead><TableRow><TableCell>时间 / 操作者</TableCell><TableCell>实体</TableCell><TableCell>动作</TableCell><TableCell>Request ID</TableCell><TableCell align="right">证据</TableCell></TableRow></TableHead><TableBody>{items.map(item=><TableRow key={item.id}><TableCell><Typography fontWeight={700}>{new Date(item.created_at).toLocaleString('zh-CN')}</Typography><Typography variant="caption">{item.actor} · {item.role}</Typography></TableCell><TableCell>{item.entity_type} #{item.entity_id}</TableCell><TableCell><code>{item.action}</code></TableCell><TableCell><code className="request-id">{item.request_id}</code></TableCell><TableCell align="right"><Tooltip title="查看前后快照与几何"><IconButton aria-label={`查看审计证据 ${item.id}`} onClick={()=>setSelected(item)}><VisibilityOutlined/></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></Box>
  <GeometryDetailDrawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?`${selected.entity_type} #${selected.entity_id} · ${selected.action}`:'审计证据'} geometry={parseGeometry(selected)} metadata={selected?{'Request ID':selected.request_id,'操作者':`${selected.actor} / ${selected.role}`,'前快照':selected.before_json,'后快照':selected.after_json,'运行元数据':selected.metadata}:undefined}/>
  </>}
