import LockOutlined from '@mui/icons-material/LockOutlined'
import { Alert, Box, Button, CircularProgress, Stack, TextField, Typography } from '@mui/material'
import { useState } from 'react'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { SurveyCanvas, type MapLayer } from '../components/common/SurveyCanvas'
import { useAuthStore } from '../stores/auth-store'
import type { GeoJSONFeature } from '../types/api'

const demoBoundary:GeoJSONFeature={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[0,0],[1000,0],[1000,600],[0,600],[0,0]]]}}
const demoLines:GeoJSONFeature={type:'Feature',properties:{},geometry:{type:'MultiLineString',coordinates:[[[20,90],[980,90]],[[20,260],[980,260]],[[20,430],[980,430]]]}}
const demoGap:GeoJSONFeature={type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[[[420,175],[590,175],[590,345],[420,345],[420,175]]]}}
const loginLayers:MapLayer[]=[{feature:demoBoundary,label:'测区',color:'#79c8c5',fill:'rgba(36,110,112,.14)',width:2},{feature:demoLines,label:'测线',color:'#e6c055',width:2,dash:[8,5]},{feature:demoGap,label:'缺口',color:'#e36b60',fill:'rgba(218,80,68,.2)',width:2}]

export function LoginPage(){const user=useAuthStore(state=>state.user);const login=useAuthStore(state=>state.login);const loading=useAuthStore(state=>state.loading);const[username,setUsername]=useState('admin');const[password,setPassword]=useState('Sonar2026!');const[error,setError]=useState('');const navigate=useNavigate();const location=useLocation();if(user)return <Navigate to="/areas" replace/>;const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');try{await login(username,password);navigate((location.state as{from?:string}|null)?.from??'/areas',{replace:true})}catch(error){setError(error instanceof Error?error.message:'登录失败')}};return <Box className="login-shell">
  <Box className="login-geometry"><SurveyCanvas layers={loginLayers} ariaLabel="示范测区、平行测线和覆盖缺口"/><Box className="login-overlay"><Typography variant="overline">OFFLINE SURVEY REVIEW</Typography><Typography component="h1">SonarScope</Typography><Typography>侧扫声呐测线覆盖规划台</Typography><Box className="coordinate-readout"><span>EPSG:32650</span><span>GRID 20 m</span><span>NO CONTROL OUTPUT</span></Box></Box></Box>
  <Box component="main" className="login-panel"><Stack component="form" onSubmit={submit} gap={2.25}><Box><Box className="brand-mark large">SS</Box><Typography variant="overline" sx={{mt:2,display:'block'}}>AUTHORIZED HYDROGRAPHIC TEAM</Typography><Typography variant="h4" sx={{mt:.5}}>进入离线工作台</Typography><Typography color="text.secondary" sx={{mt:1}}>核对测区、航迹、覆盖证据和人工复核记录。</Typography></Box><Alert severity="info" icon={<LockOutlined/>}>默认管理员账号已填入。审计员账号仅提供只读访问。</Alert>{error&&<Alert severity="error">{error}</Alert>}<TextField label="账号" value={username} onChange={event=>setUsername(event.target.value)} autoComplete="username" required/><TextField label="密码" type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" required/><Button variant="contained" type="submit" size="large" disabled={loading}>{loading?<CircularProgress size={22} color="inherit"/>:'登录'}</Button><Box className="account-choices"><Typography variant="caption" color="text.secondary">快速切换演示身份</Typography><Stack direction="row" flexWrap="wrap" gap={1}>{([['admin','管理员'],['planner','规划员'],['processor','处理员'],['reviewer','复核员'],['auditor','审计员']] as const).map(([value,label])=><Button key={value} size="small" variant="outlined" onClick={()=>{setUsername(value);setPassword('Sonar2026!')}}>{label}</Button>)}</Stack></Box></Stack></Box>
  </Box>}
