import AddRoadRounded from '@mui/icons-material/AddRoadRounded'
import ContentCopyRounded from '@mui/icons-material/ContentCopyRounded'
import LockRounded from '@mui/icons-material/LockRounded'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, LinearProgress, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { MapLegend } from '../components/common/MapLegend'
import { PageHeader } from '../components/common/PageHeader'
import { SurveyCanvas } from '../components/common/SurveyCanvas'
import { useAuth } from '../hooks/useAuth'
import { useCoverageLayers } from '../hooks/useCoverageLayers'
import { useSurveyAreaStore } from '../stores/survey-area-store'
import { useTransectPlanStore } from '../stores/transect-plan-store'
import type { GenerateTransectPlan } from '../types/transect-plan'

export function PlansPage(){const{hasRole}=useAuth();const areas=useSurveyAreaStore(state=>state.items);const fetchAreas=useSurveyAreaStore(state=>state.fetch);const{items,selected,loading,fetch,select,generate,lock,copy}=useTransectPlanStore();const[open,setOpen]=useState(false);const[drawer,setDrawer]=useState(false);const[form,setForm]=useState<GenerateTransectPlan>({survey_area_id:1,name:'自动平行测线',heading:90,line_spacing_m:160,planned_swath_m:180});useEffect(()=>{void Promise.all([fetch(),fetchAreas()])},[fetch,fetchAreas]);useEffect(()=>{if(areas[0]&&form.survey_area_id===1&&!areas.some(area=>area.id===1))setForm(value=>({...value,survey_area_id:areas[0]!.id}))},[areas,form.survey_area_id]);const area=selected?.survey_area??areas.find(value=>value.id===selected?.survey_area_id);const layers=useCoverageLayers(area,selected);const legends=useMemo(()=>layers.map(layer=>({label:layer.label,color:layer.color,pattern:layer.dash?'dash' as const:layer.fill?'fill' as const:'solid' as const})),[layers]);const submit=async()=>{await generate(form);setOpen(false)};const canEdit=hasRole('admin','survey_planner');return <>
  <PageHeader eyebrow="TRANSECT DESIGN DESK" title="测线规划器" description="从测区边界生成平行测线，锁定用于航迹导入；已锁定规划通过复制形成下一版本。" actions={<><Tooltip title="刷新"><IconButton aria-label="刷新规划" onClick={()=>void fetch()}><RefreshRounded/></IconButton></Tooltip>{canEdit&&<Button variant="contained" startIcon={<AddRoadRounded/>} onClick={()=>setOpen(true)}>生成测线</Button>}</>}/>{loading&&<LinearProgress/>}
  <Box className="planner-workspace"><Box className="plan-list" role="list" aria-label="测线规划列表"><Box className="section-heading"><Typography variant="h6">规划版本</Typography><Typography variant="caption">{items.length} 套</Typography></Box>{items.map(item=><button type="button" role="listitem" key={item.id} className={selected?.id===item.id?'plan-row active':'plan-row'} onClick={()=>select(item)}><span><strong>{item.name}</strong><small>{item.survey_area?.area_code??`AREA #${item.survey_area_id}`} · V{item.version}</small></span><span><Chip size="small" label={item.plan_state==='locked'?'已锁定':'草稿'} color={item.plan_state==='locked'?'success':'default'} variant="outlined"/><small>{item.planned_heading}° / {item.line_spacing_m} m</small></span></button>)}</Box>
    <Box className="map-workbench"><Box className="section-heading"><Box><Typography variant="overline">LOCAL CANVAS / METRE GRID</Typography><Typography variant="h6">{selected?.name??'选择规划'}</Typography></Box>{selected&&<Stack direction="row" gap={1}>{canEdit&&selected.plan_state==='draft'&&<Button size="small" startIcon={<LockRounded/>} onClick={()=>void lock(selected)}>锁定</Button>}{canEdit&&selected.plan_state==='locked'&&<Button size="small" startIcon={<ContentCopyRounded/>} onClick={()=>void copy(selected)}>复制版本</Button>}<Button size="small" onClick={()=>setDrawer(true)}>几何详情</Button></Stack>}</Box><SurveyCanvas layers={layers}/><MapLegend items={legends}/>{selected&&<Box className="metric-strip"><div><span>计划航向</span><strong>{selected.planned_heading}°</strong></div><div><span>线间距</span><strong>{selected.line_spacing_m} m</strong></div><div><span>计划扫幅</span><strong>{selected.planned_swath_m} m</strong></div><div><span>边界投影</span><strong>{area?.coordinate_system??'--'}</strong></div></Box>}</Box></Box>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>生成平行测线</DialogTitle><DialogContent><Stack gap={2} sx={{pt:1}}><FormControl><InputLabel>测区</InputLabel><Select label="测区" value={form.survey_area_id} onChange={event=>setForm({...form,survey_area_id:Number(event.target.value)})}>{areas.filter(area=>area.status!=='archived').map(area=><MenuItem key={area.id} value={area.id}>{area.area_code} · {area.name}</MenuItem>)}</Select></FormControl><TextField label="规划名称" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth type="number" label="航向 (°)" value={form.heading} onChange={event=>setForm({...form,heading:Number(event.target.value)})}/><TextField fullWidth type="number" label="线间距 (m)" value={form.line_spacing_m} onChange={event=>setForm({...form,line_spacing_m:Number(event.target.value)})}/><TextField fullWidth type="number" label="计划扫幅 (m)" value={form.planned_swath_m} onChange={event=>setForm({...form,planned_swath_m:Number(event.target.value)})}/></Stack></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>取消</Button><Button variant="contained" onClick={()=>void submit()}>生成草稿</Button></DialogActions></Dialog>
  <GeometryDetailDrawer open={drawer} onClose={()=>setDrawer(false)} title={selected?.name??'测线几何'} geometry={selected?.line_geojson} metadata={selected?{'规划状态':selected.plan_state,'计划航向':`${selected.planned_heading}°`,'线间距':`${selected.line_spacing_m} m`,'版本':selected.version}:undefined}/>
  </>}
