import CloudUploadOutlined from '@mui/icons-material/CloudUploadOutlined'
import DataObjectRounded from '@mui/icons-material/DataObjectRounded'
import RefreshRounded from '@mui/icons-material/RefreshRounded'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, IconButton, InputLabel, LinearProgress, MenuItem, Select, Stack, TextField, Tooltip, Typography } from '@mui/material'
import { useEffect, useMemo, useState } from 'react'
import { GeometryDetailDrawer } from '../components/common/GeometryDetailDrawer'
import { MapLegend } from '../components/common/MapLegend'
import { PageHeader } from '../components/common/PageHeader'
import { RunStateBadge } from '../components/common/RunStateBadge'
import { SurveyCanvas } from '../components/common/SurveyCanvas'
import { useAuth } from '../hooks/useAuth'
import { useCoverageLayers } from '../hooks/useCoverageLayers'
import { useSonarRunStore } from '../stores/sonar-run-store'
import { useTransectPlanStore } from '../stores/transect-plan-store'
import type { GeoJSONFeature } from '../types/api'
import { RUN_STATE_LABEL, RUN_TRANSITIONS, type RunState } from '../types/enums/run-state'
import type { ImportSonarRun } from '../types/sonar-run'

const defaultTrack:GeoJSONFeature={type:'Feature',properties:{source:'operator-import'},geometry:{type:'MultiLineString',coordinates:[[[30,100],[970,100]],[[30,300],[970,300]],[[30,500],[970,500]]]}}
export function RunsPage(){const{hasRole}=useAuth();const plans=useTransectPlanStore(state=>state.items);const fetchPlans=useTransectPlanStore(state=>state.fetch);const{items,selected,quality,loading,fetch,select,import:importRun,transition}=useSonarRunStore();const[open,setOpen]=useState(false);const[drawer,setDrawer]=useState(false);const now=useMemo(()=>new Date(),[]);const[form,setForm]=useState<ImportSonarRun>({transect_plan_id:1,run_code:`RUN-BROWSER-${Date.now().toString().slice(-6)}`,track_geojson:defaultTrack,actual_swath_m:170,started_at:new Date(now.getTime()-75*60000).toISOString(),ended_at:now.toISOString(),navigation_quality:'good'});useEffect(()=>{void Promise.all([fetch(),fetchPlans()])},[fetch,fetchPlans]);useEffect(()=>{const locked=plans.find(plan=>plan.plan_state==='locked');if(locked&&!plans.some(plan=>plan.id===form.transect_plan_id&&plan.plan_state==='locked'))setForm(value=>({...value,transect_plan_id:locked.id}))},[plans,form.transect_plan_id]);const area=selected?.transect_plan?.survey_area;const layers=useCoverageLayers(area,selected?.transect_plan,selected?[selected]:[]);const legends=useMemo(()=>layers.map(layer=>({label:layer.label,color:layer.color,pattern:layer.dash?'dash' as const:layer.fill?'fill' as const:'solid' as const})),[layers]);const canProcess=hasRole('admin','data_processor');const submit=async()=>{const run=await importRun(form);setOpen(false);await select(run)};const transitions=selected?RUN_TRANSITIONS[selected.run_state]??[]:[];return <>
  <PageHeader eyebrow="TRACK PROCESSING DESK" title="航迹处理台" description="导入离线 GeoJSON 航迹，核对采样与航速证据，再按质量检查状态流推进处理。" actions={<><Tooltip title="刷新"><IconButton aria-label="刷新航迹" onClick={()=>void fetch()}><RefreshRounded/></IconButton></Tooltip>{canProcess&&<Button variant="contained" startIcon={<CloudUploadOutlined/>} onClick={()=>setOpen(true)}>导入航迹</Button>}</>}/>{loading&&<LinearProgress/>}
  <Box className="run-workspace"><Box className="run-list"><Box className="section-heading"><Typography variant="h6">运行批次</Typography><Typography variant="caption">{items.length} 次导入</Typography></Box>{items.map(item=><button type="button" key={item.id} className={selected?.id===item.id?'run-row active':'run-row'} onClick={()=>void select(item)}><span><strong>{item.run_code}</strong><small>{item.transect_plan?.name??`PLAN #${item.transect_plan_id}`}</small></span><span><RunStateBadge state={item.run_state}/><small>{item.navigation_quality} · {item.actual_swath_m} m</small></span></button>)}</Box>
    <Box className="run-detail"><Box className="section-heading"><Box><Typography variant="overline">TRACK QUALITY EVIDENCE</Typography><Typography variant="h6">{selected?.run_code??'选择一次运行'}</Typography></Box><Tooltip title="查看航迹 GeoJSON"><span><IconButton aria-label="查看航迹 GeoJSON" disabled={!selected} onClick={()=>setDrawer(true)}><DataObjectRounded/></IconButton></span></Tooltip></Box><SurveyCanvas layers={layers}/><MapLegend items={legends}/>{selected&&<><Box className="metric-strip"><div><span>导航质量</span><strong>{selected.navigation_quality}</strong></div><div><span>实际扫幅</span><strong>{selected.actual_swath_m} m</strong></div><div><span>轨迹长度</span><strong>{quality?`${quality.track_length_m.toFixed(0)} m`:'读取中'}</strong></div><div><span>平均航速</span><strong>{quality?`${quality.average_speed_mps.toFixed(2)} m/s`:'读取中'}</strong></div></Box>{quality&&quality.warnings.length>0&&<Alert severity="warning" sx={{mt:2}}>{quality.warnings.join('；')}</Alert>}<Stack direction="row" useFlexGap flexWrap="wrap" gap={1} sx={{mt:2}}>{canProcess&&transitions.map(target=><Button key={target} variant={target==='rejected'?'outlined':'contained'} color={target==='rejected'?'error':'primary'} onClick={()=>void transition(selected,target,target==='rejected'?'人工质量复核驳回':'')}>{RUN_STATE_LABEL[target]}</Button>)}</Stack></>}</Box></Box>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>导入离线航迹</DialogTitle><DialogContent><Stack gap={2} sx={{pt:1}}><Stack direction={{xs:'column',sm:'row'}} gap={2}><FormControl fullWidth><InputLabel>已锁定规划</InputLabel><Select label="已锁定规划" value={form.transect_plan_id} onChange={event=>setForm({...form,transect_plan_id:Number(event.target.value)})}>{plans.filter(plan=>plan.plan_state==='locked').map(plan=><MenuItem key={plan.id} value={plan.id}>{plan.name} · V{plan.version}</MenuItem>)}</Select></FormControl><TextField fullWidth label="运行编号" value={form.run_code} onChange={event=>setForm({...form,run_code:event.target.value})}/></Stack><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth type="number" label="实际扫幅 (m)" value={form.actual_swath_m} onChange={event=>setForm({...form,actual_swath_m:Number(event.target.value)})}/><FormControl fullWidth><InputLabel>导航质量</InputLabel><Select label="导航质量" value={form.navigation_quality} onChange={event=>setForm({...form,navigation_quality:event.target.value as ImportSonarRun['navigation_quality']})}><MenuItem value="good">良好</MenuItem><MenuItem value="degraded">降级</MenuItem><MenuItem value="invalid">无效</MenuItem></Select></FormControl></Stack><Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth type="datetime-local" label="开始时间" InputLabelProps={{shrink:true}} value={form.started_at.slice(0,16)} onChange={event=>setForm({...form,started_at:new Date(event.target.value).toISOString()})}/><TextField fullWidth type="datetime-local" label="结束时间" InputLabelProps={{shrink:true}} value={form.ended_at.slice(0,16)} onChange={event=>setForm({...form,ended_at:new Date(event.target.value).toISOString()})}/></Stack><TextField label="航迹 GeoJSON" multiline minRows={8} value={JSON.stringify(form.track_geojson,null,2)} onChange={event=>{try{setForm({...form,track_geojson:JSON.parse(event.target.value)})}catch{}}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>取消</Button><Button variant="contained" onClick={()=>void submit()}>导入并校验</Button></DialogActions></Dialog>
  <GeometryDetailDrawer open={drawer} onClose={()=>setDrawer(false)} title={selected?.run_code??'航迹'} geometry={selected?.track_geojson} metadata={selected?{'运行状态':selected.run_state,'导航质量':selected.navigation_quality,'源校验和':selected.source_checksum,'版本':selected.version}:undefined}/>
  </>}
