import { Component, useEffect, useState, type ErrorInfo, type ReactNode } from 'react'
import { Alert, Button, CssBaseline, Snackbar, ThemeProvider, createTheme } from '@mui/material'
import { RouterProvider } from 'react-router-dom'
import { router } from './router'

const theme=createTheme({palette:{mode:'light',primary:{main:'#17666a',dark:'#123f42',light:'#d8eceb'},secondary:{main:'#c99624',dark:'#765711'},background:{default:'#eaf0ef',paper:'#fbfcfa'},text:{primary:'#152c2e',secondary:'#586b6c'},divider:'#cad6d4',error:{main:'#b8443c'},warning:{main:'#c38c20'},success:{main:'#35724b'},info:{main:'#376d8e'}},shape:{borderRadius:4},typography:{fontFamily:'Inter, Aptos, "Noto Sans SC", "Microsoft YaHei", sans-serif',fontSize:14,h4:{fontSize:'clamp(1.65rem, 2.2rem, 2.2rem)',fontWeight:800,lineHeight:1.15,letterSpacing:0},h5:{fontSize:'1.35rem',fontWeight:750,letterSpacing:0},h6:{fontSize:'1.05rem',fontWeight:750,letterSpacing:0},overline:{fontSize:10,fontWeight:800,lineHeight:1.5,letterSpacing:0},button:{textTransform:'none',fontWeight:700,letterSpacing:0}},components:{MuiButton:{styleOverrides:{root:{minHeight:38,boxShadow:'none'}}},MuiIconButton:{styleOverrides:{root:{width:40,height:40}}},MuiPaper:{styleOverrides:{root:{backgroundImage:'none'}}},MuiTableCell:{styleOverrides:{head:{fontWeight:800,color:'#324f51',backgroundColor:'#edf2f1'},root:{borderColor:'#d7e0df',padding:'10px 12px'}}},MuiChip:{styleOverrides:{root:{borderRadius:3}}},MuiDialog:{styleOverrides:{paper:{border:'1px solid #c9d6d4',boxShadow:'0 18px 50px rgba(20,45,46,.18)'}}}}})

export function App(){const[error,setError]=useState('');useEffect(()=>{const listener=(event:Event)=>setError((event as CustomEvent<string>).detail);window.addEventListener('api:error',listener);return()=>window.removeEventListener('api:error',listener)},[]);return <ThemeProvider theme={theme}><CssBaseline/><ErrorBoundary><RouterProvider router={router}/></ErrorBoundary><Snackbar open={Boolean(error)} autoHideDuration={6500} onClose={()=>setError('')} anchorOrigin={{vertical:'bottom',horizontal:'center'}}><Alert severity="error" variant="filled" onClose={()=>setError('')}>{error}</Alert></Snackbar></ThemeProvider>}

class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}componentDidCatch(error:Error,info:ErrorInfo){console.error('interface_error',error,info.componentStack)}render(){return this.state.failed?<main className="fatal-state"><Alert severity="error">界面渲染失败，数据未被修改。</Alert><Button variant="contained" onClick={()=>window.location.reload()}>重新加载工作台</Button></main>:this.props.children}}
